apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: so-certificate-generation
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
