apiVersion: batch/v1
kind: Job
metadata:
  name: certificate-generation
spec:
  template:
    spec:
      containers:
      - name: certificate-generation
        image: localhost:5001/certificate-generation:latest
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccount: so-certificate-generation
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
      restartPolicy: Never
