apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: so-certificate-generation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: so-certificate-generation
subjects:
- kind: ServiceAccount
  name: so-certificate-generation
